//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actividade()
        {
            this.Funcionarios = new HashSet<Funcionario>();
            this.Cargos = new HashSet<Cargo>();
            this.RegraDeRecurrencia = new RecurrenciaDeActividade();
        }
    
        public int Id { get; set; }
        public string Designacao { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataDeInicio { get; set; }
        public System.DateTime DataDeFim { get; set; }
        public bool DiaTudo { get; set; }
        public string Tipo { get; set; }
    
        public RecurrenciaDeActividade RegraDeRecurrencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargo> Cargos { get; set; }
    }
}
