//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfectacaoSalarial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AfectacaoSalarial()
        {
            this.Descricao = "";
        }
    
        public int Id { get; set; }
        public string Designacao { get; set; }
        public System.DateTime DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public TipoDeAfectacaoSalarial Tipo { get; set; }
        public decimal Valor { get; set; }
        public string Descricao { get; set; }
    }
}
