//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreira
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carreira()
        {
            this.Funcionarios = new HashSet<Funcionario>();
            this.Afectacoes = new HashSet<AfectacaoDeCarreira>();
        }
    
        public int Id { get; set; }
        public string GrupoDePessoal { get; set; }
        public string Categoria { get; set; }
        public decimal Indice { get; set; }
        public int ValorDoIndiceId { get; set; }
    
        public virtual ValorDoIndice ValorDoIndice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcionario> Funcionarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfectacaoDeCarreira> Afectacoes { get; set; }
    }
}
