//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public enum ClaseDeServico : int
    {
        TEMPO_INTEGRAL = 0,
        TEMPO_PARCIAL = 1
    }
}
