//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credencial
    {
        public int Id { get; set; }
        public NivelDeCredencial NivelDeAcesso { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public Nullable<System.DateTime> DataDeValidade { get; set; }
        public EstadoDeCredencial Estado { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
