//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public partial class DadosDeActualizacao
    {
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CargoId { get; set; }
        public Nullable<int> CarreiraId { get; set; }
        public Nullable<int> HabilitacaoLiterariaId { get; set; }
    }
}
