//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public partial class DadosPessoais
    {
        public DadosPessoais()
        {
            this.CodigoNacionalidade = "024";
            this.CodigoNaturalidade = "024-041900";
            this.Identificacao = new Documento();
            this.Contacto = new Contacto();
            this.Endereco = new Endereco();
        }
    
        public System.DateTime DataDeNascimento { get; set; }
        public EstadoCivil EstadoCivil { get; set; }
        public Genero Genero { get; set; }
        public string Nome { get; set; }
        public string NomeDaMae { get; set; }
        public string NomeDoPai { get; set; }
        public string CodigoNacionalidade { get; set; }
        public string CodigoNaturalidade { get; set; }
    
        public Documento Identificacao { get; set; }
        public Contacto Contacto { get; set; }
        public Endereco Endereco { get; set; }
    }
}
