//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Observacoes = "";
        }
    
        public TipoDeIdentificacao Tipo { get; set; }
        public System.DateTime DataDeEmissao { get; set; }
        public Nullable<System.DateTime> ValidoAte { get; set; }
        public string Numero { get; set; }
        public string EmitidoEm { get; set; }
        public string URI { get; set; }
        public string Observacoes { get; set; }
    }
}
