//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.CodigoDaRegiao = "024-041900";
        }
    
        public string CodigoDaRegiao { get; set; }
        public string Bloco { get; set; }
        public string Predio { get; set; }
        public string Rua { get; set; }
        public string Andar { get; set; }
        public string Numero { get; set; }
        public string Bairro { get; set; }
    }
}
