//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public partial class Ficheiro
    {
        public Ficheiro()
        {
            this.Nome = "";
            this.URI = "";
            this.MimeType = "";
        }
    
        public string Nome { get; set; }
        public string URI { get; set; }
        public string MimeType { get; set; }
    }
}
