//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Actividades = new HashSet<Actividade>();
            this.Actualizacoes = new HashSet<Actualizacao>();
            this.RegistosDiarios = new HashSet<RegistoDiario>();
            this.Afectacoes = new HashSet<AfectacaoDeFuncionario>();
            this.Salarios = new HashSet<Salario>();
            this.Foto = new Ficheiro();
            this.DadosPessoais = new DadosPessoais();
            this.Contrato = new Contrato();
        }
    
        public int Id { get; set; }
        public int AreaId { get; set; }
        public int CargoId { get; set; }
        public int CarreiraId { get; set; }
        public int HabilitacaoLiterariaId { get; set; }
        public string Funcao { get; set; }
    
        public Ficheiro Foto { get; set; }
        public DadosPessoais DadosPessoais { get; set; }
        public Contrato Contrato { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Carreira Carreira { get; set; }
        public virtual HabilitacaoLiteraria HabilitacaoLiteraria { get; set; }
        public virtual AreaDeTrabalho Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividade> Actividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actualizacao> Actualizacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistoDiario> RegistosDiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfectacaoDeFuncionario> Afectacoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salario> Salarios { get; set; }
        public virtual Credencial Credencial { get; set; }
    }
}
