//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public partial class RecurrenciaDeActividade
    {
        public RecurrenciaDeActividade()
        {
            this.Quantidade = 2147483647;
            this.Intervalo = 1;
        }
    
        public int Quantidade { get; set; }
        public System.DateTime Fim { get; set; }
        public long Duracao { get; set; }
        public int Intervalo { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public bool Activa { get; set; }
        public bool SemDataFinal { get; set; }
        public TipoDeRecurrencia Frequencia { get; set; }
    }
}
