//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistoDiario
    {
        public int Id { get; set; }
        public int FuncionarioId { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> HoraDeEntrada { get; set; }
        public Nullable<System.DateTime> HoraDeSaida { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
