//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RHModelContainer : DbContext
    {
        public RHModelContainer()
            : base("name=RHModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<ValorDoIndice> ValoresDosIndice { get; set; }
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Carreira> Carreiras { get; set; }
        public virtual DbSet<AfectacaoSalarial> AfectacoesSalariais { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Comuna> Comunas { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<HabilitacaoLiteraria> HabilitacoesLiterarias { get; set; }
        public virtual DbSet<AreaDeTrabalho> AreasDeTrabalho { get; set; }
        public virtual DbSet<Actividade> Actividades { get; set; }
        public virtual DbSet<Actualizacao> Actualizacoes { get; set; }
        public virtual DbSet<RegistoDiario> RegistosDiarios { get; set; }
        public virtual DbSet<Salario> Salarios { get; set; }
        public virtual DbSet<VencimentoSalarial> VencimentosSalariais { get; set; }
        public virtual DbSet<Credencial> Credenciais { get; set; }
    }
}
