//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salario()
        {
            this.Detalhes = "";
        }
    
        public int Id { get; set; }
        public int FuncionarioId { get; set; }
        public int VencimentoSalarialId { get; set; }
        public string Valor { get; set; }
        public string Detalhes { get; set; }
    
        public virtual VencimentoSalarial Vencimento { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
