//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public enum TipoDeAfectacaoSalarial : int
    {
        BASE_PERCENTAGEM = 0,
        TOTAL_PERCENTAGEM = 1,
        A_RECEBER_PERCENTAGEM = 2,
        TAXA_FIXA = 3
    }
}
