//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public enum TipoDeContrato : int
    {
        TERMO_CERTO = 1,
        TITULO_DE_PROVIMENTO = 2,
        TITULO_DE_QUADRO = 3,
        TEMPO_DETERMINADO = 4,
        DE_TRABALHOS_ESPECIAS = 5,
        ESTRANGEIROS_NÃO_RESIDENTES = 6,
        SEM_ESPECIFICAR = 0
    }
}
