//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RH.DataModel
{
    using System;
    
    public enum TipoDeRecurrencia : int
    {
        Minutely = 0,
        Hourly = 1,
        Daily = 2,
        WeekDays = 3,
        Weekly = 4,
        Monthly = 5,
        MonthlyNth = 6,
        Yearly = 7,
        YearlyNth = 8
    }
}
